server:
  port: 12306
  #ssl:
   # key-store: classpath:static/tomcat.key
   # key-store-password: 41cnissnzghyf
   # key-store-type: JKS
   # key-alias: tomcat
   # ciphers: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_RC4_128_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_RC4_128_SHA

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  datasource:
    url: jdbc:mysql://39.105.21.114:3306/Watermark?useUnicode=true&characterEncoding=utf8
    username: root
    password: 41cnissnzghyf
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapping/*Mapper.xml
    type-aliases-package: com.ocean.pojo
    config-location: classpath:configuring/mybatis-config.xml

logging:
  file:
    name: myApp.log
    path: /myApp/log

my-path:
  root: D:/die/fuck/final/backend/complete/output

rocketmq.producer:
    # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    groupName: test
    # mq的nameserver地址
    namesrvAddr: localhost:9876
    # 消息最大长度 默认 1024 * 4 (4M)
    maxMessageSize: 40960
    # 发送消息超时时间，默认 3000
    sendMsgTimeOut: 6000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 3
